artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1NpdIh_XjDK5Dmx2tilm_r3_Cfx3R5McH/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_resnet_model:
  root_dir: artifacts/prepare_resnet_model
  resnet_model_path: artifacts/prepare_resnet_model/resnet_model.pt

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/trained_model.pt